# Generated by Django 5.0.2 on 2024-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_img', models.ImageField(blank=True, null=True, upload_to='certificates', verbose_name='certificate Image')),
                ('certificate_link', models.URLField()),
                ('certificate_title', models.CharField(max_length=150, verbose_name='certificate title')),
                ('offer_by', models.CharField(max_length=150, verbose_name='certificate offer')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='project Image')),
                ('project_link', models.URLField()),
                ('project_title', models.CharField(max_length=150, verbose_name='project title')),
                ('project_associate', models.CharField(max_length=150, verbose_name='project associated with')),
                ('project_skills_gain', models.CharField(max_length=150, verbose_name='project skills')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_list', models.EmailField(max_length=254, verbose_name='recipient_list')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_img', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='topic Image')),
                ('topic_link', models.URLField()),
                ('topic_title', models.CharField(max_length=100, verbose_name='topic title')),
                ('topic_intro', models.CharField(max_length=300, verbose_name='topic intro')),
                ('topic_describtion', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
