# Generated by Django 5.0.2 on 2024-02-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipient_mail',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
